module.exports.lightSelectArray = [
  "-spotifyAlbumData.album_type",
  "-spotifyAlbumData.artists",
  "-spotifyAlbumData.available_markets",
  "-spotifyAlbumData.copyrights",
  "-spotifyAlbumData.external_ids",
  "-spotifyAlbumData.external_urls",
  "-spotifyAlbumData.genres",
  "-spotifyAlbumData.href",
  "-spotifyAlbumData.id",
  "-spotifyAlbumData.label",
  "-spotifyAlbumData.tracks",
  "-spotifyAlbumData.name",
  "-spotifyAlbumData.popularity",
  "-spotifyAlbumData.release_date",
  "-spotifyAlbumData.release_date_precision",
  "-spotifyAlbumData.type",
  "-spotifyAlbumData.uri",
].join(" ")